name: "Duino-Coin Multicore Miner"
description: "A multicore SHA-1 miner for Duino-Coin optimized for Raspberry Pi 4."
version: "1.1.0"
slug: "duco_multicore_miner"
arch:
  - aarch64
  - armv7
  - amd64
startup: "application"
boot: "auto"
options:
  username: "your_username"
  mining_key: "your_key"
  cores: 2
schema:
  username: str
  mining_key: str
  cores: int
