name: "Duino-Coin Multicore Miner"
description: "Optimized miner for RPi4"
version: "1.1.6"
slug: "duco_miner"
init: false   
arch:
  - aarch64
  - armv7
options:
  username: ""
  mining_key: ""
  cores: 2
schema:
  username: str
  mining_key: str
  cores: int
